### ISSUE TITLE
Allow Icons greater than 250x250

### ISSUE THREAD

**Issue by johandalabacka** [pcluse/AppImportAndDeploy#6]
Never versions of SCCM allows bigger icons. Don't know the limit but at least 256x256

**Comment by johandalabacka** [comment]
Commited and merged

**Comment by Robert-LTH** [comment]
On SCCM 1902 it seems that New-CMApplication returns with a parameter validation error if icon is larger then 250x250

**Comment by Robert-LTH** [comment]
This was an issue with the cmdlets in 1902. Upgrade to 1906 to fix this.
